'use strict';
const KEY='catat-uang-v1', $=s=>document.querySelector(s), uid=()=>crypto.randomUUID(), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), rupiah=n=>'Rp'+new Intl.NumberFormat('id-ID').format(n), today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}, money=n=>Number.isSafeInteger(n)&&n>=0&&n<=1e12;
const initial=()=>({version:1,wallets:[{id:uid(),name:'Tunai',initial:0}],categories:[...['Makan & Minum','Transportasi','Belanja','Tagihan','Hiburan','Kesehatan'].map(name=>({id:uid(),name,type:'expense',archived:false})),...['Gaji','Penghasilan lain'].map(name=>({id:uid(),name,type:'income',archived:false}))],transactions:[],settings:{lastWallet:'',lastBackup:null}});
function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s}
function validate(d){if(!d||d.version!==1||!Array.isArray(d.wallets)||!d.wallets.length||!Array.isArray(d.categories)||!Array.isArray(d.transactions)||d.transactions.length>100000||!d.settings)throw Error('Format cadangan tidak didukung. Pilih file JSON dari Catat Uang.');const ids=new Set(),id=x=>{if(typeof x!=='string'||!x.length||x.length>100||ids.has(x))throw Error('ID data tidak valid atau duplikat.');ids.add(x)},name=x=>typeof x==='string'&&x.trim().length>0&&x.length<=80;d.wallets.forEach(w=>{id(w.id);if(!name(w.name)||!money(w.initial))throw Error('Data dompet tidak valid.')});d.categories.forEach(c=>{id(c.id);if(!name(c.name)||!['expense','income'].includes(c.type)||typeof c.archived!=='boolean')throw Error('Data kategori tidak valid.')});d.transactions.forEach(t=>{id(t.id);if(!money(t.amount)||t.amount===0||!validDate(t.date)||!d.wallets.some(w=>w.id===t.walletId)||typeof t.note!=='string'||t.note.length>500)throw Error('Data transaksi tidak valid.');if(t.type==='transfer'){if(t.walletId===t.toWalletId||!d.wallets.some(w=>w.id===t.toWalletId))throw Error('Transfer tidak valid.')}else if(!['expense','income'].includes(t.type)||!d.categories.some(c=>c.id===t.categoryId&&c.type===t.type))throw Error('Kategori transaksi tidak cocok.')});if(d.settings.lastBackup!==null&&d.settings.lastBackup!==undefined&&(typeof d.settings.lastBackup!=='string'||isNaN(Date.parse(d.settings.lastBackup))))throw Error('Tanggal cadangan tidak valid.');if(d.settings.lastWallet!==undefined&&typeof d.settings.lastWallet!=='string')throw Error('Pengaturan tidak valid.');return d}
let data,storageBroken=false;try{const raw=localStorage.getItem(KEY);data=raw?validate(JSON.parse(raw)):initial();if(!raw)localStorage.setItem(KEY,JSON.stringify(data))}catch(e){storageBroken=true;data=initial()}
let page='beranda',month=today().slice(0,7),filter={q:'',category:'',wallet:'',type:'',from:'',to:''},toastTimer;
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
function commit(next){if(storageBroken){toast('Penyimpanan bermasalah. Ekspor data lama atau pulihkan cadangan dahulu.');return false}try{validate(next);localStorage.setItem(KEY,JSON.stringify(next));data=next;render();return true}catch(e){toast('Tidak tersimpan: '+e.message);return false}}
function update(fn){const next=structuredClone(data);fn(next);return commit(next)}
function balance(w){return data.transactions.reduce((s,t)=>s+(t.walletId===w.id?(t.type==='income'?t.amount:-t.amount):0)+(t.type==='transfer'&&t.toWalletId===w.id?t.amount:0),w.initial)}
const walletName=id=>data.wallets.find(w=>w.id===id)?.name||'Dompet',catName=id=>data.categories.find(c=>c.id===id)?.name||'Kategori';
const catIcon=id=>uiIcon(({'Makan & Minum':'food','Transportasi':'car','Belanja':'bag','Tagihan':'bill','Hiburan':'music','Kesehatan':'health','Gaji':'cash','Penghasilan lain':'cash'}[catName(id)]||'category'));
function selectedTx(){return data.transactions.filter(t=>t.date.startsWith(month))}
function empty(title,detail,symbol='↗'){return `<div class="empty"><span class="empty-symbol">${uiIcon(({"↗":"arrow","⌁":"chart","＋":"plus","☷":"ledger"})[symbol]||"category")}</span><strong>${title}</strong><p>${detail}</p></div>`}
function intro(kicker,title,extra=''){return `<div class="intro"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1></div>${extra}</div>`}
function txRows(ts){return ts.map(t=>`<button class="transaction" data-edit-tx="${esc(t.id)}"><span class="tx-icon ${t.type==='transfer'?'transfer-tag':''}">${t.type==='transfer'?uiIcon('transfer'):catIcon(t.categoryId)}</span><span class="tx-info"><strong>${esc(t.type==='transfer'?'Transfer':catName(t.categoryId))}</strong><small>${esc(walletName(t.walletId))}${t.type==='transfer'?' → '+esc(walletName(t.toWalletId)):''}${t.note?' · '+esc(t.note):''}</small></span><span class="tx-amount ${t.type==='income'?'positive':t.type==='expense'?'negative':''}">${t.type==='income'?'+':t.type==='expense'?'−':''}${rupiah(t.amount)}</span></button>`).join('')}
function home(){const ts=selectedTx(),inc=ts.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0),out=ts.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0),groups=data.categories.map(c=>({...c,total:ts.filter(t=>t.type==='expense'&&t.categoryId===c.id).reduce((s,t)=>s+t.amount,0)})).filter(c=>c.total>0).sort((a,b)=>b.total-a.total);return intro('KEUANGAN PRIBADI','Uangmu, tercatat.',`<input class="month-picker" type="month" id="month" value="${month}" aria-label="Bulan ringkasan">`)+`<section class="balance"><span class="eyebrow">TOTAL SALDO</span><span class="sticker">PUNYA KAMU <i data-icon="spark"></i></span><div class="balance-amount">${rupiah(data.wallets.reduce((s,w)=>s+balance(w),0))}</div><div class="balance-bottom"><span>${data.wallets.length} dompet · saldo saat ini</span><a href="#dompet"><b>Kelola <i data-icon="arrow"></i></b></a></div></section><div class="stats"><div class="stat"><span class="stat-label"><i data-icon="income"></i> Pemasukan</span><strong>${rupiah(inc)}</strong></div><div class="stat out"><span class="stat-label"><i data-icon="arrow"></i> Pengeluaran</span><strong>${rupiah(out)}</strong></div></div><div class="section-head"><h2>Larinya ke mana?</h2><span class="pill">${ts.filter(t=>t.type==='expense').length} TRANSAKSI</span></div><section class="panel">${groups.length?groups.map((c,i)=>`<div class="bar-row"><div class="row"><span>${esc(c.name)}</span><b>${rupiah(c.total)}</b></div><div class="bar-track"><div class="bar-fill" style="width:${c.total/out*100}%;background:${['#ff947c','#ffe34d','#a8efca','#c5baff'][i%4]}"></div></div><small class="muted">${Math.round(c.total/out*100)}% pengeluaran</small></div>`).join(''):empty('Belum ada pengeluaran','Catat pengeluaran pertamamu. Lihat polanya di sini.','⌁')}</section><div class="section-head"><h2>Catatan terbaru</h2><a class="text-link" href="#transaksi">Lihat semua <i data-icon="arrow"></i></a></div>${ts.length?txRows([...ts].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4)):empty('Mulai dari satu catatan','Beli kopi, bayar parkir, atau terima gaji. Catat lewat tombol di bawah.','＋')}<div class="tip"><span><i data-icon="spark"></i></span><span><b>Sedikit-sedikit, jadi kebaca.</b><br>Catat rutin supaya tahu ke mana uangmu pergi.</span></div>`}
function history(){let ts=data.transactions.filter(t=>(!filter.q||`${catName(t.categoryId)} ${t.note} ${walletName(t.walletId)}`.toLowerCase().includes(filter.q.toLowerCase()))&&(!filter.category||t.categoryId===filter.category)&&(!filter.wallet||t.walletId===filter.wallet||t.toWalletId===filter.wallet)&&(!filter.type||t.type===filter.type)&&(!filter.from||t.date>=filter.from)&&(!filter.to||t.date<=filter.to)).sort((a,b)=>b.date.localeCompare(a.date));let last='';return intro('SEMUA CATATAN','Transaksi.')+`<div class="filters"><input id="search" type="search" placeholder="Cari catatan atau kategori…" aria-label="Cari transaksi" value="${esc(filter.q)}"><select id="filter-category" aria-label="Filter kategori"><option value="">Semua kategori</option>${data.categories.map(c=>`<option value="${esc(c.id)}" ${filter.category===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select><select id="filter-wallet" aria-label="Filter dompet"><option value="">Semua dompet</option>${walletOptions(filter.wallet)}</select><div><label for="filter-from">Dari tanggal</label><input type="date" id="filter-from" value="${filter.from}"></div><div><label for="filter-to">Sampai tanggal</label><input type="date" id="filter-to" value="${filter.to}"></div><select id="filter-type" aria-label="Jenis transaksi"><option value="">Semua jenis</option>${[['expense','Pengeluaran'],['income','Pemasukan'],['transfer','Transfer']].map(([v,n])=>`<option value="${v}" ${filter.type===v?'selected':''}>${n}</option>`).join('')}</select><button class="secondary" id="reset-filter">Reset filter</button></div><span class="eyebrow">${ts.length} CATATAN DITEMUKAN</span>${ts.length?ts.map(t=>{const head=last!==t.date?`<div class="date-label">${new Date(t.date+'T12:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'})}</div>`:'';last=t.date;return head+txRows([t])}).join(''):empty('Belum ada catatan','Tambah transaksi atau ubah filter pencarian.','☷')}`}
function wallets(){return intro('TEMPAT UANGMU','Dompet.',`<button class="secondary scratch" id="new-wallet"><i data-icon="plus"></i> Tambah</button>`)+data.wallets.map(w=>`<div class="wallet"><div class="row"><h3><i data-icon="wallet"></i> ${esc(w.name)}</h3><button class="text-link" data-wallet="${esc(w.id)}">Edit</button></div><strong class="balance-value">${rupiah(balance(w))}</strong><div class="muted">Saldo awal ${rupiah(w.initial)}</div></div>`).join('')+`<button class="primary full scratch" id="transfer"><i data-icon="transfer"></i> TRANSFER ANTAR DOMPET</button><p class="muted">Pindahkan saldo tanpa menambah pengeluaran.</p>`}
function settings(){const days=data.settings.lastBackup?(Date.now()-Date.parse(data.settings.lastBackup))/86400000:Infinity;return intro('ATUR SESUAI KAMU','Pengaturan.')+`<section class="settings-card"><div class="row"><h2>Kategori</h2><button class="text-link" id="new-category"><i data-icon="plus"></i> Tambah</button></div>${['expense','income'].map(type=>`<p class="eyebrow">${type==='expense'?'PENGELUARAN':'PEMASUKAN'}</p>${data.categories.filter(c=>c.type===type).map(c=>`<div class="category-row ${c.archived?'archived':''}"><span>${esc(c.name)}${c.archived?' <small>(arsip)</small>':''}</span><div class="row"><button class="small-btn" data-category="${esc(c.id)}">Ubah</button><button class="small-btn" data-archive="${esc(c.id)}">${c.archived?'Aktifkan':'Arsip'}</button></div></div>`).join('')}`).join('')}</section><section class="settings-card"><h2>Cadangan data</h2><p class="muted">Simpan file JSON ke Files atau iCloud Drive. Gunakan file itu untuk memulihkan semua data.</p><div class="row"><button class="primary scratch" id="export-json"><i data-icon="download"></i> Ekspor JSON</button><button class="secondary scratch" id="import-json"><i data-icon="upload"></i> Impor JSON</button></div><input class="hide" type="file" id="import-file" accept="application/json,.json"><p class="muted">Ekspor terakhir: ${data.settings.lastBackup?esc(new Date(data.settings.lastBackup).toLocaleString('id-ID')):'belum pernah'}</p>${days>=7?'<div class="backup-warning">✳ '+(days===Infinity?'Belum ada cadangan.':'Sudah lebih dari 7 hari sejak ekspor terakhir.')+' Yuk, cadangkan datamu.</div>':''}</section><section class="settings-card"><h2>Laporan transaksi</h2><p class="muted">Ekspor semua transaksi ke CSV untuk Excel atau spreadsheet. CSV tidak digunakan untuk pemulihan.</p><button class="secondary full scratch" id="export-csv"><i data-icon="download"></i> UNDUH CSV</button></section><section class="settings-card"><h2>Hanya di perangkat ini</h2><p class="muted">Tanpa akun dan tanpa sinkronisasi. Data tersimpan pada browser atau aplikasi ini. Menghapus data situs dapat menghapus catatanmu.</p><p class="muted">Di iPhone: buka di Safari → Bagikan → Tambah ke Layar Utama. Gunakan tempat yang sama untuk mencatat dan rutin simpan cadangan.</p></section>`}
function render(){page=['beranda','transaksi','dompet','pengaturan'].includes(location.hash.slice(1))?location.hash.slice(1):'beranda';$('#main').innerHTML=(storageBroken?'<div class="backup-warning">Data lokal tidak dapat dibaca. Data lama belum diubah. Buka Pengaturan untuk ekspor data mentah atau impor cadangan.</div>':'')+({beranda:home,transaksi:history,dompet:wallets,pengaturan:settings}[page])();document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.dataset.page===page);if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});bind();paintIcons()}

function moneyInputFormat(value, caret = String(value).length) {
 const raw=String(value), digits=raw.replace(/\D/g,''), clean=digits.replace(/^0+(?=\d)/,''), removed=digits.length-clean.length;
 const left=Math.max(0,raw.slice(0,caret).replace(/\D/g,'').length-removed);
 const formatted=clean.replace(/\B(?=(\d{3})+(?!\d))/g,'.');
 let position=0,count=0;
 while(position<formatted.length&&count<left){if(/\d/.test(formatted[position]))count++;position++}
 return {value:formatted,caret:position};
}
function bindMoneyInputs(){
 document.querySelectorAll('[data-money]').forEach(input=>{
  const apply=()=>{const result=moneyInputFormat(input.value,input.selectionStart??input.value.length);input.value=result.value;input.setSelectionRange(result.caret,result.caret)};
  apply();
  input.addEventListener('input',apply);
  input.addEventListener('beforeinput',event=>{
   const start=input.selectionStart,end=input.selectionEnd;
   if(start!==end||start===null)return;
   let from,to;
   if(event.inputType==='deleteContentBackward'&&input.value[start-1]==='.') {from=Math.max(0,start-2);to=start;}
   else if(event.inputType==='deleteContentForward'&&input.value[start]==='.') {from=start;to=Math.min(input.value.length,start+2);}
   else return;
   if(!event.cancelable)return;
   event.preventDefault();input.setRangeText('',from,to,'start');apply();
  });
 });
}

function openModal(title,html){$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;paintIcons();bindMoneyInputs();if(!$('#modal').open)$('#modal').showModal()}
function closeModal(){$('#modal').close()}
function walletOptions(selected){return data.wallets.map(w=>`<option value="${esc(w.id)}" ${w.id===selected?'selected':''}>${esc(w.name)}</option>`).join('')}
function txForm(existing){if(storageBroken)return toast('Pulihkan penyimpanan melalui Pengaturan dahulu.');const t=existing||{type:'expense',amount:'',date:today(),walletId:data.settings.lastWallet||data.wallets[0].id,note:''};openModal(existing?'Edit catatan':'Catat transaksi',`<form id="tx-form"><label for="tx-type">Jenis transaksi</label><select id="tx-type">${[['expense','Pengeluaran'],['income','Pemasukan'],['transfer','Transfer']].map(([v,l])=>`<option value="${v}" ${t.type===v?'selected':''}>${l}</option>`).join('')}</select><label for="amount">Nominal (Rp)</label><input class="amount-input" id="amount" data-money type="text" inputmode="numeric" pattern="[0-9. ]+" placeholder="0" required value="${t.amount}"><div id="category-field"><div class="row"><label for="category">Kategori</label><button type="button" class="text-link" id="inline-category"><i data-icon="plus"></i> Kategori baru</button></div><select id="category"></select><div id="inline-category-box" class="hide"><label for="inline-name">Nama kategori baru</label><input id="inline-name" maxlength="80" placeholder="Contoh: Perawatan motor"><button type="button" class="small-btn" id="save-inline-category">Tambah kategori</button></div></div><label for="wallet">${t.type==='transfer'?'Dari dompet':'Dompet'}</label><select id="wallet">${walletOptions(t.walletId)}</select><div id="to-field"><label for="to-wallet">Ke dompet</label><select id="to-wallet">${walletOptions(t.toWalletId||data.wallets.find(w=>w.id!==t.walletId)?.id)}</select></div><label for="date">Tanggal</label><input id="date" type="date" required value="${t.date}"><label for="note">Catatan <span class="muted">(opsional)</span></label><textarea id="note" rows="2" maxlength="500" placeholder="Buat apa hari ini?">${esc(t.note)}</textarea><p class="error" id="form-error" role="alert"></p><div class="form-actions">${existing?'<button type="button" class="danger" id="delete-tx">Hapus</button>':''}<button class="primary scratch" type="submit">SIMPAN <i data-icon="arrow"></i></button></div></form>`);
const refreshCats=(chosen=t.categoryId)=>{const type=$('#tx-type').value;$('#category-field').classList.toggle('hide',type==='transfer');$('#to-field').classList.toggle('hide',type!=='transfer');$('#category').innerHTML=data.categories.filter(c=>c.type===type&&(!c.archived||c.id===t.categoryId)).map(c=>`<option value="${esc(c.id)}" ${c.id===chosen?'selected':''}>${esc(c.name)}${c.archived?' (arsip)':''}</option>`).join('')};refreshCats();$('#tx-type').onchange=()=>refreshCats();$('#inline-category').onclick=()=>{$('#inline-category-box').classList.toggle('hide');$('#inline-name').focus()};$('#save-inline-category').onclick=()=>{const name=$('#inline-name').value.trim(),type=$('#tx-type').value;if(!name)return;const duplicate=data.categories.find(c=>c.name.toLowerCase()===name.toLowerCase()&&c.type===type);if(duplicate){toast('Kategori sudah ada. Aktifkan jika diarsipkan.');return}const id=uid();if(update(d=>d.categories.push({id,name,type,archived:false}))){refreshCats(id);$('#inline-category-box').classList.add('hide');toast('Kategori ditambahkan')}};
$('#tx-form').onsubmit=e=>{e.preventDefault();const amount=Number($('#amount').value.replace(/[. ]/g,'')),type=$('#tx-type').value,walletId=$('#wallet').value,toWalletId=$('#to-wallet').value,categoryId=$('#category').value,date=$('#date').value;if(!money(amount)||!amount){$('#form-error').textContent='Isi nominal bulat antara Rp1 dan Rp1 triliun.';return}if(!validDate(date)){ $('#form-error').textContent='Tanggal tidak valid.';return}if(type==='transfer'&&walletId===toWalletId){$('#form-error').textContent='Pilih dua dompet yang berbeda.';return}if(type!=='transfer'&&!categoryId){$('#form-error').textContent='Tambahkan kategori terlebih dahulu.';return}const entry={id:t.id||uid(),type,amount,date,walletId,note:$('#note').value.trim(),...(type==='transfer'?{toWalletId}:{categoryId})};if(update(d=>{if(t.id)d.transactions=d.transactions.map(x=>x.id===t.id?entry:x);else d.transactions.unshift(entry);d.settings.lastWallet=walletId})){closeModal();toast('✓ Transaksi tersimpan')}};if(existing)$('#delete-tx').onclick=()=>confirmModal('Hapus transaksi?',`Catatan ${rupiah(t.amount)} akan dihapus dan saldo diperbarui.`,()=>{if(update(d=>d.transactions=d.transactions.filter(x=>x.id!==t.id))){closeModal();toast('Transaksi dihapus')}},()=>txForm(existing))}
function confirmModal(title,text,action,cancel=closeModal){openModal(title,`<p>${esc(text)}</p><div class="form-actions"><button class="secondary" id="cancel-confirm">Batal</button><button class="danger scratch" id="do-confirm">Konfirmasi</button></div>`);$('#do-confirm').onclick=action;$('#cancel-confirm').onclick=cancel}
function walletForm(id){const w=data.wallets.find(x=>x.id===id);openModal(w?'Edit dompet':'Tambah dompet',`<form id="wallet-form"><label for="wallet-name">Nama dompet</label><input id="wallet-name" maxlength="80" required value="${esc(w?.name||'')}" placeholder="Contoh: GoPay"><label for="wallet-initial">Saldo awal (Rp)</label><input id="wallet-initial" data-money type="text" inputmode="numeric" required value="${w?.initial||0}"><p class="muted">Saldo sebelum transaksi yang dicatat di aplikasi ini.</p><p class="error" id="wallet-error"></p><div class="form-actions"><button class="primary full" type="submit">Simpan dompet</button></div></form>`);$('#wallet-form').onsubmit=e=>{e.preventDefault();const name=$('#wallet-name').value.trim(),initial=Number($('#wallet-initial').value.replace(/[. ]/g,''));if(!name||!money(initial)||data.wallets.some(x=>x.id!==id&&x.name.toLowerCase()===name.toLowerCase())){$('#wallet-error').textContent='Gunakan nama unik dan saldo awal yang valid (Rp0–Rp1 triliun).';return}if(update(d=>{if(w)Object.assign(d.wallets.find(x=>x.id===id),{name,initial});else d.wallets.push({id:uid(),name,initial})})){closeModal();toast('Dompet disimpan')}}}
function categoryForm(id){const c=data.categories.find(x=>x.id===id);openModal(c?'Ubah kategori':'Tambah kategori',`<form id="cat-form"><label for="cat-name">Nama kategori</label><input id="cat-name" required maxlength="80" value="${esc(c?.name||'')}"><label for="cat-type">Jenis</label><select id="cat-type" ${c?'disabled':''}><option value="expense">Pengeluaran</option><option value="income" ${c?.type==='income'?'selected':''}>Pemasukan</option></select><p class="error" id="cat-error"></p><div class="form-actions"><button class="primary full">Simpan kategori</button></div></form>`);$('#cat-form').onsubmit=e=>{e.preventDefault();const name=$('#cat-name').value.trim(),type=$('#cat-type').value;if(!name||data.categories.some(x=>x.id!==id&&x.type===type&&x.name.toLowerCase()===name.toLowerCase())){$('#cat-error').textContent='Nama kategori kosong atau sudah digunakan.';return}if(update(d=>{if(c)d.categories.find(x=>x.id===id).name=name;else d.categories.push({id:uid(),name,type,archived:false})})){closeModal();toast('Kategori disimpan')}}}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
function exportJSON(){if(storageBroken){let raw;try{raw=localStorage.getItem(KEY)}catch(e){toast('Penyimpanan browser tidak dapat diakses.');return}if(raw)download(raw,`catat-uang-data-lama-${today()}.json`,'application/json');else toast('Tidak ada data lama yang dapat diekspor.');return}const next=structuredClone(data);next.settings.lastBackup=new Date().toISOString();download(JSON.stringify(next,null,2),`catat-uang-cadangan-${today()}.json`,'application/json');if(commit(next))toast('File cadangan dibuat. Simpan ke Files / Drive.')}
function exportCSV(){const cell=v=>'"'+String(v).replace(/^[=+@\-]/,"'$&").replace(/"/g,'""')+'"',rows=[['Tanggal','Jenis','Nominal IDR','Kategori','Dompet','Tujuan transfer','Catatan'],...data.transactions.map(t=>[t.date,{expense:'Pengeluaran',income:'Pemasukan',transfer:'Transfer'}[t.type],t.amount,t.type==='transfer'?'':catName(t.categoryId),walletName(t.walletId),t.toWalletId?walletName(t.toWalletId):'',t.note])];download('\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),`catat-uang-laporan-${today()}.csv`,'text/csv;charset=utf-8');toast('Laporan CSV dibuat')}
async function importFile(file){if(!file)return;if(file.size>20*1024*1024){toast('File terlalu besar. Maksimal 20 MB.');return}try{const incoming=validate(JSON.parse(await file.text()));openModal('Pulihkan cadangan?',`<p>File ini berisi:</p><div class="panel"><b>${incoming.transactions.length} transaksi · ${incoming.wallets.length} dompet</b><p>${incoming.categories.length} kategori</p></div><p><b>Seluruh data yang ada akan diganti.</b> Simpan cadangan lama dulu jika masih dibutuhkan.</p><button class="secondary full" id="backup-first" style="margin-top:16px"><i data-icon="download"></i> Ekspor data lama dulu</button><div class="form-actions"><button class="secondary" id="cancel-import">Batal</button><button class="danger" id="confirm-import">Ganti & pulihkan</button></div>`);$('#backup-first').onclick=exportJSON;$('#cancel-import').onclick=closeModal;$('#confirm-import').onclick=()=>{try{localStorage.setItem(KEY,JSON.stringify(incoming));data=incoming;storageBroken=false;render();closeModal();toast('✓ Semua data berhasil dipulihkan')}catch(e){toast('Tidak dapat menyimpan. Data belum diganti.')}}}catch(e){toast('Impor ditolak: '+(e instanceof SyntaxError?'File JSON tidak valid.':e.message))}}
function bind(){document.querySelectorAll('[data-edit-tx]').forEach(b=>b.onclick=()=>txForm(data.transactions.find(t=>t.id===b.dataset.editTx)));document.querySelectorAll('[data-wallet]').forEach(b=>b.onclick=()=>walletForm(b.dataset.wallet));document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>categoryForm(b.dataset.category));document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>{if(update(d=>{const c=d.categories.find(c=>c.id===b.dataset.archive);c.archived=!c.archived}))toast('Kategori diperbarui')});const on=(s,f)=>{if($(s))$(s).onclick=f};on('#new-wallet',()=>walletForm());on('#new-category',()=>categoryForm());on('#transfer',()=>{if(data.wallets.length<2)return toast('Tambahkan satu dompet lagi untuk transfer.');txForm({type:'transfer',amount:'',date:today(),walletId:data.wallets[0].id,toWalletId:data.wallets[1].id,note:''})});on('#export-json',exportJSON);on('#export-csv',exportCSV);on('#import-json',()=>$('#import-file').click());if($('#import-file'))$('#import-file').onchange=e=>importFile(e.target.files[0]);if($('#month'))$('#month').onchange=e=>{if(e.target.value){month=e.target.value;render()}};for(const [id,key]of [['filter-category','category'],['filter-wallet','wallet'],['filter-from','from'],['filter-to','to'],['filter-type','type']])if($('#'+id))$('#'+id).onchange=e=>{filter[key]=e.target.value;render()};if($('#search'))$('#search').oninput=e=>{const start=e.target.selectionStart;filter.q=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(start,start)};on('#reset-filter',()=>{filter={q:'',category:'',wallet:'',type:'',from:'',to:''};render()})}
$('#add').onclick=()=>txForm();$('#close-modal').onclick=closeModal;window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});window.addEventListener('storage',e=>{if(e.key===KEY){try{if(!e.newValue)throw Error();data=validate(JSON.parse(e.newValue));storageBroken=false;closeModal();render();toast('Data diperbarui dari tab lain')}catch{storageBroken=true;closeModal();render();toast('Penyimpanan berubah. Pulihkan cadangan sebelum mencatat.')}}});render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'start_transaction_entry',title:'Buka pencatatan transaksi',description:'Membuka formulir transaksi. Pengguna mengisi dan menyimpan melalui formulir; tool ini belum membuat transaksi.',inputSchema:{type:'object',properties:{type:{type:'string',enum:['expense','income','transfer']}},required:['type'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!['expense','income','transfer'].includes(input.type))throw Error('Jenis transaksi tidak valid.');if(storageBroken)throw Error('Penyimpanan lokal bermasalah.');if(input.type==='transfer'&&data.wallets.length<2)throw Error('Tambahkan dompet tujuan terlebih dahulu.');txForm({type:input.type,amount:'',date:today(),walletId:data.settings.lastWallet||data.wallets[0].id,note:''});return {status:'form_open',saved:false,type:input.type}}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}catch{}}
